import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';


@Component({
  selector: 'app-preditor',
  templateUrl: './preditor.component.html',
  styleUrls: ['./preditor.component.css']
})
export class PreditorComponent implements OnInit {

  showPredict = false
  prediction: any = false
  itemSelected: any = false
  msgAlert: string = ""

  bairros: string[] = []
  marcas: string[] = []
  dias: string[] = []
  sexos: string[] = []
  periodos: string[] = []

  predictForm = new FormGroup({
    nome: new FormControl(''),
    bairro: new FormControl(''),
    dia: new FormControl(''),
    periodo: new FormControl(''),
    marca: new FormControl(''),
    idade: new FormControl(''),
    sexo: new FormControl('')
  });

  httpOptions = {
    headers: new HttpHeaders({
      'Content-Type':  'application/json'
    })
  };

  constructor(private http: HttpClient) { }

  onSubmit(){
    
    let data = this.predictForm.value

    console.log(data)

    this.http.post('http://localhost:5002/predict', data, this.httpOptions).subscribe(
      resp => {
        this.prediction = resp
        console.log(this.prediction)
        this.showPredict = true
        this.build_msg()
      },
      err => {
        console.log("Deu Ruim")
        console.log(err)
      }
    ); 

  }

  build_msg(){
    this.msgAlert = "Baseado em seu perfil e destino a maior probabilidade de Furto/Roubo é em " + this.prediction[9].label +
                    " com " +  this.prediction[9].value + "%, " + this.predictForm.value.nome + " fique atento pois " + this.predictForm.value.sexo +
                    " de " + this.predictForm.value.idade + " anos, com celular da marca " + this.predictForm.value.marca + ", no bairro " + 
                    this.predictForm.value.bairro + " e no período "+ this.predictForm.value.periodo + ", tem uma grande chance de " + 
                    "sofrer roubo/furto de celular em " + this.prediction[9].label + ", não dê bobeira guarde seu celular e mantenha-se perto de outras pessoas." 

  }

  ngOnInit(): void {
    this.build_bairros()
    this.build_marcas()
    this.build_dias()
    this.build_sexos()
    this.build_periodos()
    //this.init_mock()
  }

  showInfo(item: any){
    this.itemSelected = item

    var desc = null
    switch (this.itemSelected.id) {
      case 1:
        desc = "Institutos, Juntas, Fóruns e Salas de Reuniões";break;
      case 2:
        desc = "Clínicas, Hospitais, Consultórios e Postos de Saúde";break;
      case 3:
        desc = "Casas Noturnas, Estádios, Boate e Museus";break;
      case 4:
        desc = "Restaurantes, Lanchonete, Bares e Pizzarias";break;
      case 5:
        desc = "Veículos de Aplicativo e Particulares";break;
      case 6:
        desc = "Mercados, Lojas, Oficinas e Floriculturas";break;
      case 7:
        desc = "Casa, Apartamento, Hotel e Pensão";break;
      case 8:
        desc = "Ônibus, Metrô, Lotações e pontos de embarque/desembarque";break;
      case 9:
        desc = "Praças, Vielas, Cortiços e Rua";break;
      case 10:
        desc = "Escolas Fundamentais, Faculdades, Universidades e Escola de Idiomas";break;
    }

    this.itemSelected.desc = desc

    console.log(this.itemSelected)

  }

  init_mock(){
    this.prediction = [
      {id: 10, label: 'Escolas / Universidade', position: 0, value: '5.43'},
      {id: 1, label: 'Escritórios', position: 1, value: '5.43'},
      {id: 2, label: 'Saúde', position: 2, value: '5.46'},
      {id: 5, label: 'Transporte Privado', position: 3, value: '5.84'},
      {id: 8, label: 'Transporte Público', position: 4, value: '5.90'},
      {id: 4, label: 'Alimentação', position: 5, value: '5.92'},
      {id: 6, label: 'Estabelecimentos Comerciais / Industrias', position: 6, value: '5.93'},
      {id: 7, label: 'Residência / Hospedagem', position: 7, value: '6.03'},
      {id: 3, label: 'Entreterimento', position: 8, value: '10.52'},
      {id: 9, label: 'Via Pública', position: 9, value: '43.53'}]

    this.showPredict = true
  }

  build_sexos(){
    this.sexos = ['HOMEM', 'MULHER']
  }

  build_dias(){
    this.dias = ['SEGUNDA',
    'TERCA',
    'QUARTA',
    'QUINTA',
    'SEXTA',
    'SABADO',
    'DOMINGO',]
  }

  build_periodos(){
    this.periodos = ['MANHA',
    'TARDE',
    'NOITE',
    'MADRUGADA']
  }

  build_marcas(){
    this.marcas = ['Samsung', 
    'Asus', 
    'Motorola', 
    'Outros', 
    'LG', 
    'Apple', 
    'Xiaomi', 
    'Huawei', 
    'Positivo', 
    'Nokia', 
    'Multilaser', 
    'Alcatel', 
    'Siemens', 
    'Microsoft', 
    'BLU', 
    'Lenovo', 
    'ZTE', 
    'Sony', 
    'BlackBerry']
  }

  build_bairros(){
    this.bairros = ['REPUBLICA', 
        'SE', 
        'LIBERDADE', 
        'BELA VISTA', 
        'JARDIM JUSSARA', 
        'BRAS', 
        'CENTRO HISTORICO DE SAO PAULO', 
        'CENTRO', 
        'CAMBUCI', 
        'CANINDE', 
        'MOOCA', 
        'VILA CLARICE', 
        'CONSOLACAO', 
        'SANTA IFIGENIA', 
        'BOM RETIRO', 
        'LUZ', 
        'PONTE PEQUENA', 
        'SANTA CECILIA', 
        'SANTA EFIGENIA', 
        'CAMPOS ELISEOS', 
        'JARDIM ATALIBA LEONEL', 
        'VILA BUARQUE', 
        'CENTRO CAPITAL', 
        'JARDIM PAULISTA', 
        'JARDIM PRIMAVERA', 
        'HIGIENOPOLIS', 
        'CERQUEIRA CESAR', 
        'VILA MARIANA', 
        'ACLIMACAO', 
        'BARRA FUNDA', 
        'RURAL', 
        'PARAISO', 
        'ALTO DO PARI', 
        'IPIRANGA', 
        'JARDIM VILA MARIANA', 
        'VILA MONUMENTO', 
        'JARDIM DA GLORIA', 
        'QUARTA PARADA', 
        'BELEM', 
        'BELENZINHO', 
        'AGUA RASA', 
        'PARI', 
        'CIDADE JULIA', 
        'JARDIM AMERICA', 
        'JARDIM COLINA', 
        'AGUA FUNDA', 
        'VILA CLEMENTINO', 
        'SAUDE', 
        'VILA DA SAUDE', 
        'MOEMA', 
        'VILA GUMERCINDO', 
        'BOSQUE DA SAUDE', 
        'MIRANDOPOLIS', 
        'PLANALTO PAULISTA', 
        'INDIANOPOLIS', 
        'CHACARA INGLESA', 
        'VILA DOM PEDRO I', 
        'VILA INDEPENDENCIA', 
        'VILA SUZANA', 
        'VILA PRUDENTE', 
        'PARQUE DA MOOCA', 
        'VILA VERA', 
        'SACOMA', 
        'VILA BRASILINA', 
        'VILA MORAES', 
        'JARDIM DOMITILA', 
        'CURSINO', 
        'JARDIM MARIA ESTELA', 
        'VILA NANCY', 
        'VILA DAS MERCES', 
        'VILA BRASILIO MACHADO', 
        'CAMPO BELO', 
        'VILA ALEXANDRIA', 
        'SANTO AMARO', 
        'PARQUE COLONIAL', 
        'VILA CONGONHAS', 
        'JABAQUARA', 
        'ITAIM BIBI', 
        'CIDADE MONCOES', 
        'JARDIM AEROPORTO', 
        'VILA OLIMPIA', 
        'BROOKLIN', 
        'VILA GUARANI', 
        'VILA SANTA CATARINA', 
        'JARDIM JABAQUARA', 
        'JARDIM ITACOLOMI', 
        'RESIDENCIAL TAIPAS', 
        'PARQUE JABAQUARA', 
        'VILA GUARANI (ZONA SUL)', 
        'JARDIM ORIENTAL', 
        'VILA GUARANI (Z SUL)', 
        'VILA MASCOTE', 
        'VILA CAMPESTRE', 
        'VILA MONTE ALEGRE', 
        'CIDADE ADEMAR', 
        'IBIRAPUERA', 
        'PARQUE IBIRAPUERA', 
        'JARDIM LUZITANIA', 
        'JARDIM BELCITO', 
        'JARDIM CLIMAX', 
        'VILA LIVIERO', 
        'VILA AGUA FUNDA', 
        'JARDIM SANTA CRUZ (SACOMA)', 
        'VILA HELIOPOLIS', 
        'SAO JOAO CLIMACO', 
        'CIDADE NOVA HELIOPOLIS', 
        'VILA NATALIA', 
        'VILA NAIR', 
        'BROOKLIN PAULISTA', 
        'VILA CORDEIRO', 
        'JARDIM DAS ACACIAS', 
        'JARDIM NOVO MUNDO', 
        'VILA NOVA CONCEICAO', 
        'PARQUE DAS NACOES', 
        'VILA CLARA', 
        'VILA DO ENCONTRO', 
        'JARDIM ANGELA (ZONA SUL)', 
        'JARDIM PRUDENCIA', 
        'VILA FACHINI', 
        'CIDADE VARGAS', 
        'CIDADE DOMITILA', 
        'JARDIM MIRIAM', 
        'AMERICANOPOLIS', 
        'SUMAREZINHO', 
        'LAPA', 
        'PERDIZES', 
        'VILA ROMANA', 
        'VILA ANASTACIO', 
        'LAPA DE BAIXO', 
        'PARQUE INDUSTRIAL TOMAS EDSON', 
        'SUMARE', 
        'AGUA BRANCA', 
        'PIRITUBA', 
        'VILA POMPEIA', 
        'PINHEIROS', 
        'ALTO DE PINHEIROS', 
        'JARDIM UNIVERSIDADE PINHEIROS', 
        'VILA MADALENA', 
        'JARDIM DAS BANDEIRAS', 
        'PACAEMBU', 
        'JARDIM EUROPA', 
        'JARDIM PAULISTANO', 
        'CHACARA ITAIM', 
        'VARZEA DA BARRA FUNDA', 
        'POMPEIA', 
        'VILA LOURDES', 
        'JARDIM SANTO ELIAS', 
        'JAGUARA', 
        'JARAGUA', 
        'SAO DOMINGOS', 
        'PARQUE ANHANGUERA', 
        'JARDIM MARISA', 
        'VILA SANTA EDWIGES', 
        'VILA JAGUARA', 
        'VILA FIAT LUX', 
        'CITY AMERICA', 
        'JARDIM REGINA', 
        'JARDIM IDEAL', 
        'VILA JARAGUA', 
        'JARDIM MANGALOT', 
        'MORUMBI', 
        'VILA SONIA', 
        'BUTANTA', 
        'JARDIM OLYMPIA', 
        'JARDIM DAS VERTENTES', 
        'FERREIRA', 
        'CIDADE JARDIM', 
        'VILA PROGREDIOR', 
        'JARDIM MORUMBI', 
        'JARDIM LEONOR', 
        'REAL PARQUE', 
        'INSTITUTO DE PREVIDENCIA', 
        'JARDIM VIANA', 
        'VILA ANDRADE', 
        'VILA TRAMONTANO', 
        'JARDIM PANORAMA', 
        'CAMPO LIMPO', 
        'JARDIM VALE DAS VIRTUDES', 
        'CAPAO REDONDO', 
        'VILA PREL', 
        'JD SAO LUIS', 
        'JARDIM PARIS', 
        'PARQUE ESMERALDA', 
        'PARQUE IPE', 
        'PARQUE MUNHOZ', 
        'JARDIM PIRACUAMA', 
        'UMARIZAL', 
        'JARDIM NADIR', 
        'VILA PIRAJUSSARA', 
        'PARQUE REGINA', 
        'VILA MARACANA', 
        'JARDIM MARIA VIRGINIA', 
        'JARDIM VISTA LINDA', 
        'JARDIM SAO JANUARIO', 
        'JARDIM ELIZABETH', 
        'JARDIM HELGA', 
        'JARDIM IPE', 
        'JARDIM BOM REFUGIO', 
        'JARDIM GERMANIA', 
        'JARDIM CATANDUVA', 
        'JARDIM UMARIZAL', 
        'CIDADE AUXILIADORA', 
        'PARQUE FLAMENGO', 
        'JARDIM DAS PALMAS', 
        'PARQUE ARARIBA', 
        'JARDIM LEONIDAS MOREIRA', 
        'JARDIM INGA', 
        'VILA FANTON', 
        'PERUS', 
        'VILA PERUS', 
        'ANHANGUERA', 
        'RECANTO DOS HUMILDES', 
        'JARDIM IPANEMA (ZONA OESTE)', 
        'SOL NASCENTE', 
        'JARDIM BOA VISTA(ANHANGUERA)', 
        'JARDIM SHANGRILA (ZONA NORTE)', 
        'JARDIM SANTA FE (ZONA OESTE)', 
        'RESIDENCIAL SOL NASCENTE', 
        'JARDIM ADELFIORE', 
        'JARDIM NINHO VERDE II', 
        'JARDIM JARAGUA (SAO DOMINGOS)', 
        'JARDIM RINCAO', 
        'JARDIM SANTA LUCRECIA', 
        'CHACARA JARAGUA', 
        'VILA SANTA CRUZ', 
        'CONJUNTO HABITACIONAL TURISTICA', 
        'MORADA DO SOL', 
        'VILA SANTO ANTONIO', 
        'VILA MALVINA', 
        'PARADA', 
        'CONJUNTO RESIDENCIAL BUTANTA', 
        'JARDIM PINHEIROS', 
        'RIO PEQUENO', 
        'JARDIM SARAH', 
        'JARDIM IVANA', 
        'JARDIM ESMERALDA', 
        'JARDIM ESTER', 
        'VILA SAO DOMINGOS', 
        'PARQUE DOS PRINCIPES', 
        'JARDIM BOA VISTA (ZONA OESTE)', 
        'JARDIM BONFIGLIOLI', 
        'JARDIM ESTER YOLANDA', 
        'RAPOSO TAVARES', 
        'JARDIM SAO JORGE', 
        "JARDIM D'ABRIL", 
        'JARDIM DRACENA', 
        'JARDIM CLAUDIA', 
        'JARDIM ARPOADOR', 
        'JARDIM JOAO XXIII', 
        'JARDIM CAMBARA', 
        'CONJUNTO PROMORAR RAPOSO TAVARES', 
        'VILA PEREIRA BARRETO', 
        'VILA MIRANTE', 
        'JARDIM FELICIDADE (ZONA OESTE)', 
        'VILA PIRITUBA', 
        'JARDIM IRIS', 
        'JARDIM CIDADE PIRITUBA', 
        'VILA ZAT', 
        'VILA PEREIRA CERCA', 
        'PIQUERI', 
        'JARDIM SAO JOSE', 
        'JARDIM SYDNEY', 
        'NOSSA SENHORA DO O', 
        'JARDIM AMPLIACAO', 
        'JARDIM LONDRINA', 
        'PARAISO DO MORUMBI', 
        'JARDIM MONTE KEMEL', 
        'PARQUE DO MORUMBI', 
        'JARDIM JAMAICA', 
        'FAZENDA MORUMBI', 
        'JARDIM TABOAO', 
        'VILA LEOPOLDINA', 
        'VILA HAMBURGUESA', 
        'JAGUARE', 
        'ALTO DA LAPA', 
        'VILA BUTANTA', 
        'VILA UNIVERSITARIA', 
        'VILA LAGEADO', 
        'VILA SAO SILVESTRE (ZONA LESTE)', 
        'CIDADE SAO FRANCISCO', 
        'BALNEARIO MAR PAULISTA', 
        'VILA POLOPOLI', 
        'SANTANA', 
        'JARDIM SAO PAULO', 
        'VILA GUILHERME', 
        'VILA PAIVA', 
        'VILA MARIA', 
        'CARANDIRU', 
        'JARDIM NOVO PANTANAL', 
        'JARDIM SAO PAULO(ZONA NORTE)', 
        'CASA VERDE', 
        'CASA VERDE BAIXA', 
        'VILA BARUEL', 
        'IMIRIM', 
        'LIMAO', 
        'VILA CELESTE', 
        'VILA MARIA BAIXA', 
        'JARDIM JAPAO', 
        'TREMEMBE', 
        'MANDAQUI', 
        'VILA ALBERTINA', 
        'TUCURUVI', 
        'VILA MAZZEI', 
        'JARDIM FRANCA', 
        'JARDIM DAS PEDRAS', 
        'AGUA FRIA', 
        'FREGUESIA DO O', 
        'VILA MARIA TRINDADE', 
        'VILA SAO VICENTE', 
        'MOINHO VELHO', 
        'BRASILANDIA', 
        'VILA CAVATON', 
        'VILA BRUNA', 
        'VILA IORIO', 
        'JARDIM DAS GRACAS', 
        'VILA ARCADIA', 
        'VILA CRUZ DAS ALMAS', 
        'CACHOEIRINHA', 
        'VILA PALMEIRAS', 
        'JARDIM PERI', 
        'VILA DOS ANDRADES', 
        'JARDIM ANTARTICA', 
        'PARQUE NOVO GRAJAU', 
        'PARQUE MANDAQUI', 
        'VILA PEDRA BRANCA', 
        'VILA MEDEIROS', 
        'CIDADE BRASIL', 
        'JACANA', 
        'PARADA INGLESA', 
        'JARDIM BRASIL', 
        'VILA SANTA TEREZINHA (ZONA NORTE)', 
        'VILA CONSTANCA', 
        'PARQUE EDU CHAVES', 
        'CASA VERDE ALTA', 
        'VILA SANTA MARIA', 
        'VILA BANDEIRANTES', 
        'PARQUE BELEM', 
        'JARDIM AZANO II', 
        'SITIO MORRO GRANDE', 
        'VILA NINA', 
        'CONJUNTO PROMORAR ESTRADA DA PARADA', 
        'JARDIM CENTENARIO', 
        'VILA SOUZA', 
        'JARDIM ELISA MARIA', 
        'JARDIM MODELO', 
        'VILA GALVAO', 
        'FURNAS', 
        'VILA NOVA GALVAO', 
        'VILA NILO', 
        'JARDIM RECANTO VERDE', 
        'VILA PAULISTANA', 
        'PARQUE CASA DE PEDRA', 
        'JARDIM BRASIL (ZONA NORTE)', 
        'TRES CRUZES', 
        'JARDIM PAULISTANO (ZONA NORTE)', 
        'JARDIM PIRITUBA', 
        'JARDIM GUARANI', 
        'JARDIM VIVAN', 
        'JARDIM MAGGI', 
        'PARQUE NACOES UNIDAS', 
        'CONJUNTO RESIDENCIAL ELISIO TEIXEIRA LEITE', 
        'PARQUE TAIPAS', 
        'VILA TERESINHA', 
        'LOTEAMENTO CITY JARAGUA', 
        'JARDIM LIDER', 
        'VILA NOVA PARADA', 
        'JARDIM VISTA ALEGRE', 
        'VILA SABRINA', 
        'TATUAPE', 
        'JARDIM ANDARAI', 
        'PARQUE NOVO MUNDO', 
        'VILA BEATRIZ', 
        'CANGAIBA', 
        'VILA MATILDE', 
        'PENHA', 
        'CHACARA CALIFORNIA', 
        'VILA SAO GERALDO', 
        'VILA CENTENARIO', 
        'PENHA DE FRANCA', 
        'VILA PAULISTANIA', 
        'VILA CARLOS DE CAMPOS', 
        'VILA RUI BARBOSA', 
        'VILA SANTO HENRIQUE', 
        'CHACARA SEIS DE OUTUBRO', 
        'VILA SANTANA', 
        'PQ. NOVO MUNDO', 
        'VILA CALIFORNIA', 
        'VILA DALILA', 
        'CIDADE PATRIARCA', 
        'ARTUR ALVIM', 
        'CARRAO', 
        'VILA ARICANDUVA', 
        'VILA GUILHERMINA', 
        'VILA TALARICO', 
        'JARDIM PEDRA BRANCA', 
        'VILA REGENTE FEIJO', 
        'SAO LUCAS', 
        'VILA FORMOSA', 
        'JARDIM ADUTORA', 
        'JARDIM ANALIA FRANCO', 
        'CIDADE MAE DO CEU', 
        'COLONIA (ZONA LESTE)', 
        'VILA CARRAO', 
        'VILA GOMES CARDIM', 
        'CHACARA SANTO ANTONIO (ZONA LESTE)', 
        'VILA FERNANDES', 
        'SAPOPEMBA', 
        'VILA PAULO SILAS', 
        'VILA ALPINA', 
        'VILA CENTRAL', 
        'JARDIM TERESA', 
        'VILA DIVINA PASTORA', 
        'JARDIM INDEPENDENCIA', 
        'VILA EMA', 
        'VILA MACEDOPOLIS', 
        'PARQUE SAO JORGE', 
        'VILA ZILDA', 
        'QUINTA DA PAINEIRA', 
        'VILA GRACIOSA', 
        'JARDIM IBITIRAMA', 
        'VILA CLAUDIA', 
        'VILA BERTIOGA', 
        'ALTO DA MOOCA', 
        'JARDIM TEXTIL', 
        'PARQUE DO LAGO', 
        'JARDIM ANGELA', 
        'PARQUE NOVO SANTO AMARO', 
        'CIDADE IPAVA', 
        'VILA BOM JARDIM', 
        'PARQUE SANTO ANTONIO', 
        'COLONIA (ZONA SUL)', 
        'PARQUE BOLOGNE', 
        'JARDIM VERA CRUZ(ZONA SUL)', 
        'JARDIM DO LAGO', 
        'BARONESA', 
        'PARQUE DAS CEREJEIRAS', 
        'JARDIM TAMOIO', 
        'PARQUE UNIVERSITARIO ESPIRITA', 
        'JARDIM SANTA MARGARIDA', 
        'JARDIM COPACABANA', 
        'CIDADE DUTRA', 
        'GRAJAU', 
        'PEDREIRA', 
        'JARDIM GUANHEMBU', 
        'PARQUE RESIDENCIAL COCAIA', 
        'PARQUE COCAIA', 
        'JARDIM DOS ALAMOS', 
        'JARDIM REPRESA', 
        'JARDIM MONTE VERDE', 
        'PARQUE AMERICA', 
        'PARQUE GRAJAU', 
        'PARQUE PLANALTO', 
        'JARDIM FLORESTA', 
        'PARQUE ALTO DO RIO BONITO', 
        'JARDIM MALIA II', 
        'JARDIM ELIANA', 
        'SOCORRO', 
        'INTERLAGOS', 
        'VILA SOCORRO', 
        'JARDIM DOS LAGOS', 
        'JARDIM DAS FLORES', 
        'VELEIROS', 
        'VARZEA DE BAIXO', 
        'CHACARA SANTO ANTONIO (ZONA SUL)', 
        'CAMPO GRANDE', 
        'JARDIM PROMISSAO', 
        'VILA GERTRUDES', 
        'ALTO DA BOA VISTA', 
        'GRANJA JULIETA', 
        'JARDIM DOM BOSCO', 
        'PARELHEIROS', 
        'JARDIM IPORA', 
        'JARDIM SILVEIRA', 
        'SITIO MATSUMURA', 
        'JARDIM NOVO PARELHEIROS', 
        'JARDIM CASA GRANDE', 
        'JARDIM NOVO HORIZONTE', 
        'JARDIM MARILDA', 
        'PARQUE TAMARI', 
        'EMBURA', 
        'JARDIM VERA CRUZ', 
        'JD. DAS FONTES', 
        'CUPECE', 
        'VILA MARARI', 
        'JARDIM CIDALIA', 
        'VILA CONSTANCIA', 
        'VILA SAO PAULO', 
        'JARDIM DO COLEGIO', 
        'CONJUNTO HABITACIONAL INSTITUTO ADVENTISTA', 
        'JARDIM FRATERNIDADE', 
        'JARDIM MACEDONIA', 
        'CHACARA SANTA MARIA', 
        'JARDIM ELEDY', 
        'JARDIM GUARUJA', 
        'JARDIM DAS ROSAS', 
        'PARQUE FERNANDA', 
        'PARQUE INDEPENDENCIA', 
        'PIRAJUSSARA', 
        'JARDIM DAS ROSAS (ZONA OESTE)', 
        'CHACARA DO CONDE', 
        'CONJUNTO HABITACIONAL PARQUE VALO VELHO II', 
        'JARDIM SAO BENTO NOVO', 
        'JARDIM DOM JOSE', 
        'JARDIM AMALIA', 
        'JARDIM MITSUTANI', 
        'JARDIM CLARICE', 
        'JARDIM MARIA SAMPAIO', 
        'JARDIM IAE', 
        'JARDIM AURELIO', 
        'VILA DA PAZ', 
        'JARDIM REGIS', 
        'JARDIM SATELITE', 
        'JARDIM SANTA CRUZ (CAMPO GRANDE)', 
        'JARDIM SONIA (ZONA SUL)', 
        'JARDIM SAO CARLOS (ZONA SUL)', 
        'JARDIM ORLY', 
        'JARDIM UMUARAMA', 
        'VILA BABY', 
        'JARDIM ITAPURA', 
        'VILA JOANIZA', 
        'VILA CAMPO GRANDE', 
        'JARDIM MYRNA', 
        'JARDIM LUCELIA', 
        'JARDIM ORBAM', 
        'JARDIM ITATIAIA', 
        'JARDIM CAMPINAS', 
        'PARQUE DEIZY', 
        'PARQUE BRASIL', 
        'JARDIM SAO RAFAEL', 
        'PARQUE BRISTOL', 
        'JARDIM SAO PEDRO (ZONA SUL)', 
        'VILA NATAL', 
        'JARDIM NORONHA', 
        'VILA SAO JOSE', 
        'CHACARA COCAIA', 
        'JARDIM SAO BERNARDO', 
        'JARDIM CAPELINHA', 
        'JARDIM SAO LUIS', 
        'JARDIM CASABLANCA', 
        'CHACARA SANTANA', 
        'PARQUE MARIA HELENA', 
        'JARDIM DUPRAT', 
        'JARDIM SANTA EFIGENIA', 
        'JARDIM SAO LUIZ', 
        'JD. NOVO SANTO AMARO', 
        'VILA DAS BELEZAS', 
        'JARDIM VERGUEIRO', 
        'JARDIM MONTE AZUL', 
        'JARDIM MIRANTE', 
        'JARDIM MAZZA', 
        'BALNEARIO SAO FRANCISCO', 
        'JARDIM SANTA TEREZINHA (PEDREIRA)', 
        'PARQUE DOROTEIA', 
        'ELDORADO', 
        'VILA GUACURI', 
        'JARDIM SANTA TEREZINHA (ZONA SUL)', 
        'VILA ALMEIDA', 
        'JARDIM TAQUARAL', 
        'JARDIM ANHANGUERA', 
        'JURUBATUBA', 
        'JARDIM SANTA BRANCA', 
        'VILA SAO PEDRO', 
        'VILA EMIR', 
        'VILA ARRIETE', 
        'JARDIM CAMPO GRANDE', 
        'JARDIM DOS PRADOS', 
        'VILA SOFIA', 
        'JARDIM MARAJOARA', 
        'VILA GEA', 
        'JOSE BONIFACIO', 
        'CONJUNTO RESIDENCIAL JOSE BONIFACIO', 
        'ITAQUERA', 
        'JARDIM HELENA', 
        'GUAIANASES', 
        'JARDIM SAO PEDRO', 
        'SAO MIGUEL', 
        'PARQUE PAULISTANO', 
        'VILA CURUCA', 
        'VILA MARA', 
        'SAO MIGUEL PAULISTA', 
        'CIDADE NOVA SAO MIGUEL', 
        'VILA ROSARIA', 
        'CIDADE NITRO QUIMICA', 
        'VILA BARBOSA', 
        'PONTE RASA', 
        'ERMELINO MATARAZZO', 
        'VILA RE', 
        'VILA MARIETA', 
        'PARQUE CISPER', 
        'JARDIM TRES MARIAS', 
        'VILA VELHA', 
        'ENGENHEIRO GOULART', 
        'VILA RIO BRANCO', 
        'VILA CARMOSINA', 
        'PARQUE DO CARMO', 
        'VILA CAMPANELA', 
        'VILA PROGRESSO (ZONA LESTE)', 
        'CIDADE KEMEL', 
        'ITAIM PAULISTA', 
        'JARDIM MIRAGAIA', 
        'JARDIM CAMARGO NOVO', 
        'VILA GRANADA', 
        'JARDIM DAS OLIVEIRAS', 
        'JARDIM AIMORE', 
        'JARDIM LAURA', 
        'VILA ROSEIRA II', 
        'JARDIM NELIA', 
        'JARDIM NELIA IV', 
        'JARDIM BARTIRA', 
        'JARDIM CAMPO LIMPO (ZONA NORTE)', 
        'JARDIM SAO LUIS (ZONA LESTE)', 
        'PARQUE INDUSTRIAL', 
        'JARDIM DOS IPES', 
        'JARDIM MAIA', 
        'JARDIM FLUMINENSE', 
        'JARDIM ROMANO', 
        'JARDIM JUA', 
        'JARDIM PONTE RASA', 
        'PARQUE BOTURUSSU', 
        'VILA PONTE RASA', 
        'JARDIM MATARAZZO', 
        'VILA JACUI', 
        'PARQUE DAS FLORES', 
        'JARDIM COTINHA', 
        'JARDIM KERALUX', 
        'VILA PARANAGUA', 
        'JARDIM NAIR', 
        'LIMOEIRO', 
        'PARQUE CRUZEIRO DO SUL', 
        'JARDIM DAS CAMELIAS', 
        'JARDIM PEDRO JOSE NUNES', 
        'VILA NOVA UNIAO', 
        'JARDIM SANTANA', 
        'JARDIM SAO SEBASTIAO', 
        'CIDADE ANTONIO ESTEVAO DE CARVALHO', 
        'PARQUE PAINEIRAS', 
        'VILA TAQUARI', 
        'BURGO PAULISTA', 
        'JARDIM LIDERANCA', 
        'CIDADE LIDER', 
        'PARQUE ARTUR ALVIM', 
        'CONJUNTO HABITACIONAL PADRE JOSE DE ANCHIETA', 
        'VILA NHOCUNE', 
        'VILA SANTA TERESA', 
        'PARQUE SANTA RITA', 
        'JARDIM NAZARETH', 
        'LAJEADO', 
        'VILA CURUCA VELHA', 
        'PARQUE DOM JOAO NERI', 
        'JARDIM ROBRU', 
        'VILA NOVA CURUCA', 
        'PARQUE GUAIANAZES', 
        'JARDIM CAROLINA', 
        'JARDIM ETELVINA', 
        'GUAIANAZES', 
        'VILA CHABILANDIA', 
        'JARDIM QUISISANA (VILA NOVA CURUCA)', 
        'NUCLEO CARVALHO DE ARAUJO', 
        'PARADA XV DE NOVEMBRO', 
        'LAGEADO', 
        'VILA IOLANDA(LAJEADO)', 
        'JARDIM DO CAMPO', 
        'JARDIM FANGANIELLO', 
        'VILA MINERVA', 
        'ARICANDUVA', 
        'VILA BANCARIA', 
        'JARDIM VILA FORMOSA', 
        'JARDIM GRIMALDI', 
        'VILA ANTONIETA', 
        'PARQUE SANTO EDUARDO', 
        'PARQUE DOS BANCARIOS', 
        'VILA PRIMAVERA', 
        'JARDIM COLORADO', 
        'CONJUNTO HABITACIONAL SITIO CONCEICAO', 
        'JARDIM PEROLA II', 
        'JARDIM SOARES', 
        'CIDADE TIRADENTES', 
        'VILA POPULAR', 
        'VILA PRINCESA ISABEL', 
        'CONJUNTO RESIDENCIAL PRESTES MAIA', 
        'CONJUNTO HABITACIONAL JUSCELINO KUBITSCHEK', 
        'JARDIM SAO PAULO(ZONA LESTE)', 
        'SAO MATEUS', 
        'IGUATEMI', 
        'SAO RAFAEL', 
        'VILA ESTER', 
        'CIDADE SAO MATEUS', 
        'PARQUE SAO LOURENCO', 
        'CIDADE SATELITE SANTA BARBARA', 
        'JARDIM NOVE DE JULHO', 
        'JARDIM NOVA VITORIA I', 
        'JARDIM DA CONQUISTA', 
        'JARDIM VILA CARRAO', 
        'VILA BELA', 
        'JARDIM NOVA CONQUISTA', 
        'JARDIM NOVA HARMONIA', 
        'JARDIM AUGUSTO', 
        'PARQUE BOA ESPERANCA', 
        'JARDIM DA LARANJEIRA (ZONA LESTE)', 
        'JARDIM IGUATEMI', 
        'TERCEIRA DIVISAO', 
        'JARDIM ALTO ALEGRE (SAO RAFAEL)', 
        'CONJUNTO HABITACIONAL FAZENDA DO CARMO', 
        'JARDIM NOSSA SENHORA DO CARMO', 
        'JARDIM HELIAN', 
        'CONJUNTO HABITACIONAL BARRO BRANCO II', 
        'CHACARA SANTA ETELVINA', 
        'JARDIM SAO PAULO (ZONA LESTE)', 
        'CONJUNTO HABITACIONAL SANTA ETELVINA II', 
        'CONJUNTO HABITACIONAL SANTA ETELVINA III', 
        'JARDIM VITORIA', 
        'CONJUNTO HABITACIONAL INACIO MONTEIRO', 
        'JARDIM SANTO ANDRE', 
        'PARQUE SAO RAFAEL', 
        'JARDIM SAO FRANCISCO', 
        'PQ DAS FLORES', 
        'JARDIM MARILIA', 
        'JARDIM SANTA TEREZINHA (ZONA LESTE)', 
        'JARDIM ARICANDUVA', 
        'JARDIM SANTA TERESINHA', 
        'PARQUE SAVOI CITY', 
        'JARDIM BRASILIA', 
        'JARDIM MARINGA', 
        'JARDIM SANTA MARIA', 
        'JARDIM SAPOPEMBA', 
        'JARDIM SANTA ADELIA', 
        'CIDADE CENTENARIO', 
        'JARDIM TIETE', 
        'FAZENDA DA JUTA', 
        'JARDIM IMPERADOR (ZONA LESTE)', 
        'JARDIM PARAGUACU', 
        'JARDIM VERA CRUZ(ZONA LESTE)', 
        'JARDIM COMERCIAL', 
        'JARDIM COTIANA', 
        'VILA ELZE', 
        'VILA TOLSTOI', 
        'VILA VIRGINIA', 
        'JARDIM GUAIRACA', 
        'VILA MENDES', 
        'JARDIM PLANALTO', 
        'VILA RENATO (ZONA LESTE)', 
        'VILA SAPOPEMBA', 
        'VILA CARDOSO FRANCO', 
        'VILA INDUSTRIAL', 
        'CONJUNTO RESIDENCIAL SITIO ORATORIO', 
        'CID KEMEL', 
        'CONCEICAO', 
        'VALO VELHO', 
        'JARDIM SALETE', 
        'VILA MOINHO VELHO', 
        'CATUMBI', 
        'BOM R', 
        'JARDIM DA SAUDE', 
        'JARDIM PREVIDENCIA', 
        'VILA VERMELHA', 
        'VILA PAULISTA', 
        'CHACARA MONTE ALEGRE', 
        'NOVA PIRAJU', 
        'JARDIM PETROPOLIS', 
        'VILA MIRA', 
        'JARDIM IMPERADOR (ZONA SUL)', 
        'JARDIM VERGUEIRO (SACOMA)', 
        'PARQUE FONGARO', 
        'VILA ARAPUA', 
        'VILA MARTE', 
        'VILA ANGLO BRASILEIRA', 
        'COQUEIRO', 
        'VL NOVA CONCEICAO', 
        'JARDIM PEROLA III', 
        'PARQUE SAO DOMINGOS', 
        'JARDIM EVEREST', 
        'JARDIM COLOMBO', 
        'VILA NOVA DAS BELEZAS', 
        'JARDIM AVENIDA', 
        'JARDIM ANA MARIA', 
        'JARDIM ROSANA', 
        'JARDIM SAMARA', 
        'VILA PLANA', 
        'JARDIM CAMPO LIMPO', 
        'PARQUE REBOUCAS', 
        'JARDIM YPE', 
        'JARDIM JARAGUA', 
        'VILA CAIUBA', 
        'JARDIM TAIPAS', 
        'VILA DOS PALMARES', 
        'VILA AURORA', 
        'JARDIM RIZZO', 
        'JARDIM BOA VISTA', 
        'JARDIM VITORIA REGIA', 
        'JARDIM PARQUE MORUMBI', 
        'JARDIM FONTE DO MORUMBI', 
        'SUPER QUADRA MORUMBI', 
        'PARQUE RESIDENCIAL DA LAPA', 
        'CHORA MENINO', 
        'SANTA TERESINHA', 
        'JARDIM DAS LARANJEIRAS', 
        'VILA MARIA ALTA', 
        'JARDIM VIRGINIA BIANCA', 
        'LAUZANE PAULISTA', 
        'HORTO FLORESTAL', 
        'VILA MIRIAM', 
        'ITABERABA', 
        'PARQUE MONTEIRO SOARES', 
        'VILA BANCARIA MUNHOZ', 
        'VILA PORTUGUESA', 
        'VILA NOVA CACHOEIRINHA', 
        'VILA DIONISIA', 
        'VILA GUSTAVO', 
        'VILA NOVA MAZZEI', 
        'PARQUE VITORIA', 
        'VILA NIVI', 
        'GUAPIRA', 
        'VILA SANTISTA', 
        'VILA SIQUEIRA (ZONA NORTE)', 
        'JARDIM PEREIRA LEITE', 
        'JARDIM MARACANA', 
        'PARQUE SAO LUIS', 
        'JARDIM MARISTELA', 
        'VILA JOAO BATISTA', 
        'JARDIM ELISIO', 
        'JARDIM SANTO ONOFRE', 
        'JARDIM PALMARES (ZONA NORTE)', 
        'JARDIM FELICIDADE (ZONA NORTE)', 
        'VILA AYROSA', 
        'ESTANCIA JARAGUA', 
        'VILA PENTEADO', 
        'PARQUE PAN AMERICANO', 
        'CIDADE NITRO OPERARIA', 
        'JARDIM SAO JOAO (JARAGUA)', 
        'JARDIM JULIETA', 
        'VILA ESPERANCA', 
        'VILA DO SOL', 
        'JARDIM PIRATININGA', 
        'VILA CANERO', 
        'VILA DIVA (ZONA LESTE)', 
        'VILA SANTA CLARA', 
        'VILA AZEVEDO', 
        'VILA NOVA MANCHESTER', 
        'JARDIM INDEPENDENCIA (SAO PAULO)', 
        'PARQUE SAO LUCAS', 
        'VILA MOREIRA', 
        'JARDIM AVELINO', 
        'PARQUE DA VILA PRUDENTE', 
        'MIAMI PAULISTA', 
        'JARDIM HERCULANO', 
        'CHACARA DA ENSEADA', 
        'JARDIM SAO FRANCISCO(ZONA SUL)', 
        'PARQUE SANTA BARBARA', 
        'CHACARA SONHO AZUL', 
        'VILA CALU', 
        'RIO BONITO', 
        'JARDIM GAIVOTAS', 
        'JARDIM PROGRESSO', 
        'JARDIM PRAINHA', 
        'PQ DAS NACOES', 
        'JARDIM DAS IMBUIAS', 
        'CHACARA GAIVOTAS', 
        'VILA CALIFORNIA(ZONA SUL)', 
        'VILA CRUZEIRO', 
        'VILA SAO FRANCISCO (ZONA SUL)', 
        'JARDIM CORDEIRO', 
        'JARDIM DOS EUCALIPTOS', 
        'JARDIM MARIA FERNANDES', 
        'COLONIA', 
        'RECANTO CAMPO BELO', 
        'PARQUE MARIA FERNANDES', 
        'VILA IMPERIO', 
        'VILA AUREA', 
        'CONJUNTO HABITACIONAL JARDIM SAO BENTO', 
        'JARDIM RANIELE', 
        'JARDIM DAS ROSAS (ZONA SUL)', 
        'VILA CLELIA', 
        'JARDIM MARIANE', 
        'JARDIM IRAPIRANGA', 
        'PARQUE SONIA', 
        'JARDIM LILAH', 
        'JARDIM IMBE', 
        'JARDIM SORAIA', 
        'JARDIM DOS BICHINHOS', 
        'JARDIM SAO BENEDITO', 
        'JARDIM MARCEL', 
        'JARDIM PEDREIRA', 
        'VILA DOS ANDRADAS', 
        'VILA DO CASTELO', 
        'JARDIM CONSORCIO', 
        'JARDIM PALMARES (ZONA SUL)', 
        'JARDIM DOS MANACAS', 
        'JARDIM TRES CORACOES', 
        'JARDIM SANTA FE (ZONA SUL)', 
        'CHACARA SAO SILVESTRE', 
        'JARDIM ALPINO', 
        'JARDIM GUANABARA', 
        'JARDIM ICARAI', 
        'JARDIM SHANGRILA (ZONA SUL)', 
        'VILA SAO JOSE (CIDADE DUTRA)', 
        'JARDIM VARGINHA', 
        'JARDIM SOMARA', 
        'JARDIM FIGUEIRA GRANDE', 
        'JARDIM SAO LUIS (ZONA OESTE', 
        'JARDIM NOVA GERMANIA', 
        'GUARAPIRANGA', 
        'JARDIM NOVO SANTO AMARO', 
        'JARDIM SELMA', 
        'JARDIM RUBILENE', 
        'JARDIM DAS LARANJEIRAS (ZONA SUL)', 
        'JARDIM LUSO', 
        'JARDIM BELGICA', 
        'JARDIM ITAPEVA', 
        'CAMPININHA', 
        'VILA ISA', 
        'VILA COSMOPOLITA', 
        'COHAB JOSE BONIFACIO', 
        'VILA AMERICANA', 
        'JARDIM DANFER', 
        'JARDIM POPULAR', 
        'VILA BUENOS AIRES', 
        'VILA SILVIA', 
        'JARDIM UBIRAJARA (ZONA LESTE)', 
        'FAZENDA ITAIM', 
        'JARDIM INDAIA', 
        'PARQUE SANTA AMELIA', 
        'VILA ITAIM', 
        'VILA SEABRA', 
        'VILA MONTE SANTO', 
        'JARDIM SAO CARLOS (ZONA LESTE)', 
        'VILA NORMA', 
        'JARDIM CASA PINTADA', 
        'VILA VERDE', 
        'JARDIM NORDESTE', 
        'VILA REGINA', 
        'PARQUE GUARANI', 
        'JARDIM ITAPEMIRIM', 
        'COHAB PADRE MANOEL DA NOBREGA', 
        'JARDIM GUAIANAZES', 
        'NUCLEO LAGEADO', 
        'VILA ODETE', 
        'VILA YOLANDA', 
        'JARDIM AURORA (ZONA LESTE)', 
        'CAPAO DO EMBIRA', 
        'JARDIM CATARINA', 
        'VILA GUARANI(ZONA LESTE)', 
        'JARDIM IVA', 
        'CONJUNTO HABITACIONAL BARREIRA GRANDE', 
        'VILA NOVA YORK', 
        'JARDINS RECANTO DAS ROSAS', 
        'VILA IOLANDA II', 
        'CONJUNTO HABITACIONAL JUSCELINO KUBITSCHECK DE OLIVEIRA', 
        'JARDIM SAO JOSE (SAO MATEUS)', 
        'JARDIM SAO CRISTOVAO', 
        'JARDIM RICARDO', 
        'JARDIM MARIA LIDIA', 
        'FAZENDA CAGUACU', 
        'GLEBA DO PESSEGO', 
        'VILA MARILENA', 
        'CONJUNTO HABITACIONAL CASTRO ALVES', 
        'RECANTO VERDE DO SOL', 
        'JARDIM RODOLFO PIRANI', 
        'CONJUNTO PROMORAR RIO CLARO', 
        'PARQUE SAVOY CITY', 
        'JARDIM ELIANE', 
        'JARDIM SAO ROBERTO', 
        'CONJUNTO HABITACIONAL TEOTONIO VILELA', 
        'JARDIM ANGELA (ZONA LESTE)', 
        'PARQUE RESIDENCIAL ORATORIO', 
        'VILA NOVA', 
        'JARDIM MIMAR', 
        'PARQUE SANTA MADALENA', 
        'JARDIM SANTO ANTONIO', 
        'PARQUE DOM PEDRO', 
        'ANHAGABAU', 
        'CHACARA KLABIN', 
        'VILA BRASIL', 
        'BAIRRO JARDINS', 
        'VILA SANTA EULALIA', 
        'PARQUE IMPERIAL', 
        'VILA SANTO ESTEFANO', 
        'JARDIM SANTA EMILIA', 
        'VILA UBERABINHA', 
        'BROOKLIN NOVO', 
        'JARDINS', 
        'VILA GUEDES', 
        'VILA BOACAVA', 
        'VILA DOS REMEDIOS', 
        'JARDIM CELESTE', 
        'VILA MORSE', 
        'JARDIM CAPAO REDONDO', 
        'CAXINGUI', 
        'VILA ERNESTO', 
        'CHACARA NOSSA SENHORA DO BOM CONSELHO', 
        'JARDIM SAO JOAO (ZONA NORTE)', 
        'CONJUNTO CITY JARAGUA', 
        'JARDIM DA CONQUISTA (ZONA OESTE)', 
        'VILA ANTONIO', 
        'JARDIM ALVORADA (ZONA OESTE)', 
        'JARDIM ROSA MARIA', 
        'JARDIM PAULO VI', 
        'JARDIM RAPOSO TAVARES', 
        'VILA BONILHA NOVA', 
        'PARAISOPOLIS', 
        'BELA ALIANCA', 
        'CONTINENTAL', 
        'VILA NOVA ALBA', 
        'PARQUE PERUCHE', 
        'VILA ESTER (ZONA NORTE)', 
        'JARDIM PARAISO', 
        'PARQUE JANDAIA', 
        'VILA MARINA', 
        'FREGUESIA', 
        'VILA ROQUE', 
        'VILA DOM PEDRO II', 
        'SITIO DO MORRO', 
        'JARDIM PRINCESA', 
        'JARDIM CECY', 
        'SITIO DO PIQUERI', 
        'VILA FIDALGO', 
        'VILA CAROLINA', 
        'JARDIM TREMEMBE', 
        'JARDIM DAMASCENO', 
        'VILA BRASILANDIA', 
        'JARDIM PARANA', 
        'JARDIM VITORIA REGIA (ZONA NORTE)', 
        'JARDIM CAROMBE', 
        'PARQUE VILA MARIA', 
        'JARDIM GUANCA', 
        'JARDIM AMERICA DA PENHA', 
        'CHACARA MAFALDA', 
        'J ANALIA FRANCO', 
        'PARQUE SEVILHA', 
        'VILA LUCIA', 
        'CHACARA BELENZINHO', 
        'VILA GUIOMAR', 
        'JARDIM BRASILIA (ZONA NORTE)', 
        'RIVIEIRA', 
        'JARDIM KAGOHARA', 
        "M'BOI MIRIM", 
        'CANTINHO DO CEU', 
        'COHAB BRIGADEIRO FARIA LIMA', 
        'JARDIM KIOTO', 
        'PARQUE ATLANTICO', 
        'JARDIM SANTO AMARO', 
        'JARDIM ALMEIDA', 
        'JARDIM SAO GONCALO', 
        'JARDIM MARCELO', 
        'VILA INGLESA', 
        'JARDIM SAO MANOEL', 
        'JARDIM MARACA', 
        'JARDIM ANA LUCIA', 
        'JARDIM REPUBLICA', 
        'JARDIM COLONIAL', 
        'VILA INDUSTRIAL ( VILA NOVA CURUCA)', 
        'JARDIM MARTINI', 
        'JARDIM ALMEIDA PRADO', 
        'JARDIM ALVORADA (ZONA SUL)', 
        'BALNEARIO SAO JOSE', 
        'JARDIM RAMALA', 
        'JARDIM REIMBERG', 
        'PARQUE SAO MIGUEL', 
        'JARDIM MYRNA II', 
        'JARDIM VAZ DE LIMA', 
        'JARDIM LIDIA', 
        'JARDIM THOMAZ', 
        'PIRAPORINHA', 
        'VILA MISSIONARIA', 
        'PRAIA DO LEBLON', 
        'JARDIM CASTELO', 
        'USINA PIRATININGA', 
        'CONJUNTO RESIDENCIAL JOSE BONI', 
        'CHACARA TRES MENINAS', 
        'VILA PEDROSO', 
        'JARDIM SAO VICENTE', 
        'CIDADE SAO MIGUEL', 
        'VILA DOUTOR EIRAS', 
        'VILA COSTA MELO', 
        'JARDIM SILVA TELES', 
        'VILA SILVA TELES', 
        'JARDIM SAO MARTINHO', 
        'JARDIM PANTANAL', 
        'VILA AIMORE', 
        'JARDIM MARIA RITA', 
        'VILA NOVA TERESA', 
        'CONJUNTO HABITACIONAL AGUIA DE HAIA', 
        'CONJUNTO HABITACIONAL A. E. CARVALHO', 
        'JARDIM NORMA', 
        'JARDIM LAJEADO', 
        'VILA FUKUYA', 
        'JARDIM CAGUASSU', 
        'JARDIM TANGO', 
        'JARDIM DO DIVINO', 
        'JARDIM SAO JOAO', 
        'JARDIM MARILU', 
        'VILA CHUCA', 
        'VILA PAULISTA I', 
        'JARDIM SANTA ETELVINA', 
        'JARDIM FERNANDES', 
        'JARDIM IPANEMA(ZONA LESTE)', 
        'FAZENDA ARICANDUVA', 
        'PARQUE MARIA LUIZA', 
        'JARDIM ITAPOLIS', 
        'CONJUNTO PROMORAR SAPOPEMBA', 
        'JARDIM DONA SINHA', 
        'JARDIM SAO GABRIEL', 
        'PARQUE LUIS MUCCIOLO', 
        'VILA CUNHA BUENO', 
        'VILA NOVA PAULICEIA', 
        'JARDIM ROSINHA', 
        'CUMBICA', 
        'PONTE GRANDE', 
        'JARDIM CAMBIRI', 
        'PADROEIRA', 
        'JARDIM PAPAI NOEL', 
        'PQ. DOM PEDRO II', 
        'VILA CARAGUATA', 
        'VILA CARIOCA', 
        'MOOCA DISTRICT', 
        'JARDIM EDITH', 
        'PTO PAULISTA', 
        'VILA GUARANI(ZONA SUL)', 
        'VL SACOMA', 
        'VILA N. CONCEICAO', 
        'JARDIM COIMBRA', 
        'JARDIM SUL SAO PAULO', 
        'JARDIM DIONISIO', 
        'VILA IPOJUCA', 
        'SICILIANO', 
        'VILA HOMERO', 
        'JARDIM LIBANO', 
        'JARDIM TRUSSARDI', 
        'JARDIM PERI PERI', 
        'JARDIM OLINDA', 
        'J MARIA ROSA', 
        'JARDIM MARTINICA', 
        'SITIO ITABERABA I', 
        'JARDIM SANTA FE', 
        'JARDIM DO RUSSO', 
        'SUBPREFEITURA DE PERUS', 
        'VILA RENATO', 
        'VILA SAO LUIS(ZONA OESTE)', 
        'VILA ISOLINA MAZZEI', 
        'VILA GOUVEIA', 
        'PARQUE ANHEMBI', 
        'JARDIM CACHOEIRA', 
        'JARDIM DENISE', 
        'VILA VITORIO MAZZEI', 
        'JARDIM CARLU', 
        'VILA RENATO (ZONA NORTE)', 
        'JARDIM PERI NOVO', 
        'JARDIM ONDINA', 
        'JARDIM FELICIDADE(ZONA NORTE)', 
        'CORONEL SEZEFREDO FAGUNDES', 
        'JARDIM FONTALIS', 
        'JARDIM PORTAL I E II', 
        'VILA NOVA CAROLINA', 
        'JARDIM APUANA', 
        'JARDIM FRANCISCO MENDES', 
        'PARADA DE TAIPAS', 
        'VILA ITABERABA', 
        'JARDIM ALVINA', 
        'CONJUNTO PROMORAR VILA MARIA III', 
        'PQ SAO JORGE', 
        'JARDIM HERCILIA', 
        'VILA SANTO ESTEVAO', 
        'JARDIM CAPELA', 
        'CHACARA FLORIDA', 
        'JARDIM NAKAMURA', 
        'JARDIM WILMA FLOR', 
        'JARDIM BANDEIRANTES', 
        'JARDIM CLIPER', 
        'PARQUE RESIDENCIAL DOS LAGOS', 
        'JD PRIMAVERA', 
        'JARDIM ARISTOCRATA', 
        'CONJUNTO HABITACIONAL BRIGADEIRO FARIA LIMA', 
        'JARDIM MARABA', 
        'CHACARA SANTO ANTONIO', 
        'JARDIM CARAVELAS', 
        'JARDIM DO CENTRO', 
        'CASA GRANDE', 
        'JARDIM SABIA II', 
        'VILA FAZZEONI', 
        'JD SAO BENTO NOVO', 
        'JARDIM WANDA', 
        'JARDIM NITEROI', 
        'JARDIM MORAIS PRADO', 
        'PARQUE SAO PAULO', 
        'VILA QUINTANA', 
        'JARDIM AZANO I', 
        'JARDIM BEATRIZ', 
        'PARQUE GUARAPIRANGA', 
        'JARDIM IRACEMA', 
        'JARDIM CELIA (ZONA SUL)', 
        'JARDIM APURA', 
        'JARDIM SABARA', 
        'VILA LEONOR', 
        'JARDIM BONIFACIO', 
        'VILA SINHA', 
        'JARDIM PENHA', 
        'VILA DANUBIO AZUL', 
        'VILA PAULISTA II', 
        'CHACARA DO SOL', 
        'VILA SAO JOSE (ITAIM PAULISTA)', 
        'JARDIM JARAGUA (ITAIM PAULISTA)', 
        'JARDIM NOEMIA', 
        'VILA HELENA', 
        'VILA SAO FRANCISCO', 
        'JARDIM BOM PASTOR', 
        'JARDIM GALLI', 
        'JARDIM SAO JOAO (GUAIANAZES)', 
        'PARQUE CENTRAL', 
        'RECANTO ALEGRE', 
        'JARDIM ROSELI', 
        'JARDIM PEROLA I', 
        'JARDIM LIMOEIRO', 
        'VILA NOVA MAUA', 
        'JARDIM BRASILIA (ZONA LESTE)', 
        'J CLEMENTINO', 
        'JD CAMARGO VELHO', 
        'VILA DEODORO', 
        'JARDIM BRASIL (ZONA SUL)', 
        'C MONCOES', 
        'JARDIM LOURDES (ZONA SUL)', 
        'VILA CAPELA', 
        'NORTE', 
        'VILA MANGALOT', 
        'CHACARA SAO JOAO', 
        'JARDIM MARIA DUARTE', 
        'JARDIM SAO ROQUE', 
        'JARDIM BRONZATO', 
        'VILA FRANCA', 
        'CHACARA SANTO HUBERTUS', 
        'JARDIM MONTE BELO', 
        'INDUSTRIAL ANHANGUERA', 
        'VILA SULINA', 
        'VILA INDIANA', 
        'JARDIM DABRIL', 
        'VILA RIBEIRO DE BARROS', 
        'EMBU DAS ARTES', 
        'VILA AMERICA', 
        'JARDIM MONJOLO', 
        'SAMPAIO', 
        "JARDIM JOANA D'ARC", 
        'JARDIM GUAPIRA', 
        'JARDIM FLOR DE MAIO', 
        'FLOR DE MAIO', 
        'VL SABRINA', 
        'JARDIM ARACATI', 
        'JARDIM MARQUESA', 
        'VILA REPRESA', 
        'JARDIM PRESIDENTE', 
        'JARDIM CRUZEIRO', 
        'JARDIM IPANEMA (ZONA SUL)', 
        'JARDIM HIPICO', 
        'RANCHO DO ABILIO', 
        'VILA ERNA', 
        'JARDIM SANTO ANTONINHO', 
        'VILA MARGARETH', 
        'JARDIM CAMPO DOS FERREIROS', 
        'JARDIM SONIA INGA', 
        'JARDIM IMPERIO', 
        'VILA CASTELO', 
        'JARDIM UBIRAJARA', 
        'PARQUE SAO JOSE', 
        'JARDIM BOA VISTA (ZONA SUL)', 
        'JARDIM LETICIA', 
        'JARDIM SANTA JOSEFINA', 
        'VILA ANHANGUERA', 
        'VILA SANTA TERESINHA', 
        'VILA NITRO OPERARIA', 
        'JARDIM LISBOA', 
        'JARDIM IPANEMA (ZONA LESTE', 
        'VILA JUREMA', 
        'VILA ALABAMA', 
        'JARDIM CAMPOS', 
        'VILA SIQUEIRA (ZONA LESTE)', 
        'VILA SANTA INES', 
        'JD SAO NIOCOLAU', 
        'VILA SUICA', 
        'VILA SAO FRANCISCO (ZONA LESTE)', 
        'VILA CONCEICAO', 
        'JARDIM NOVO CARRAO', 
        'VILA SAO JOSE (GUAIANAZES)', 
        'GUAIANZES', 
        'VILA ZEFIRA', 
        'JARDIM CINCO DE JULHO', 
        'VILA GIL', 
        'PALANQUE', 
        'CIPO']    
  }

}
